export const locations = [
    {
        title: 'House',
        href: 'house-cleaning',
        slug: 'house-cleaning',
        meta: {},
        items: [
            { title: 'Benowa', slug: 'benowa' },
            { title: 'Broadbeach', slug: 'broadbeach' },
            { title: 'Burleigh Heads', slug: 'burleigh-heads' },
            { title: 'Burleigh Waters', slug: 'burleigh-waters' },
            { title: 'Coolangatta', slug: 'coolangatta' },
            { title: 'Currumbin', slug: 'currumbin' },
            { title: 'Coomera', slug: 'coomera' },
            { title: 'Helensvale', slug: 'helensvale' },
            { title: 'Hope Island', slug: 'hope-island' },
            { title: 'Labrador', slug: 'labrador' },
            { title: 'Mermaid Waters', slug: 'mermaid-waters' },
            { title: 'Miami', slug: 'miami' },
            { title: 'Mudgeeraba', slug: 'mudgeeraba' },
            { title: 'Nerang', slug: 'nerang' },
            { title: 'Ormeau', slug: 'Ormeau' },
            { title: 'Oxenford', slug: 'oxenford' },
            { title: 'Pacific Pines', slug: 'pacific-pines' },
            { title: 'Palm Beach', slug: 'palm-beach' },
            { title: 'Paradise Point', slug: 'paradise-point' },
            { title: 'Robina', slug: 'robina' },
            { title: 'Runaway Bay', slug: 'runaway-bay' },
            { title: 'Southport', slug: 'southport' },
            { title: 'Surfers Paradise', slug: 'surfers-paradise' },
            { title: 'Upper Coomera', slug: 'upper-coomera' },
            { title: 'Varsity Lakes', slug: 'varsity-lakes' },
        ],
    },
    {
        title: 'Bond',
        href: 'bond-cleaning',
        slug: 'bond-cleaning',
        meta: {},
        items: [
            { title: 'Benowa', slug: '' },
            { title: 'Broadbeach', slug: 'broadbeach' },
            { title: 'Burleigh Heads', slug: 'burleigh-heads' },
            { title: 'Burleigh Waters', slug: 'burleigh-waters' },
            { title: 'Coolangatta', slug: 'coolangatta' },
            { title: 'Currumbin', slug: 'currumbin' },
            { title: 'Helensvale', slug: 'helensvale' },
            { title: 'Hope Island', slug: 'hope-island' },
            { title: 'Labrador', slug: 'labrador' },
            { title: 'Mermaid Waters', slug: 'mermaid-waters' },
            { title: 'Miami', slug: 'miami' },
            { title: 'Mudgeeraba', slug: 'mudgeeraba' },
            { title: 'Nerang', slug: 'nerang' },
            { title: 'Ormeau', slug: 'Ormeau' },
            { title: 'Oxenford', slug: 'oxenford' },
            { title: 'Pacific Pines', slug: 'pacific-pines' },
            { title: 'Palm Beach', slug: 'palm-beach' },
            { title: 'Paradise Point', slug: 'paradise-point' },
            { title: 'Robina', slug: 'robina' },
            { title: 'Runaway Bay', slug: 'runaway-bay' },
            { title: 'Southport', slug: 'southport' },
            { title: 'Surfers Paradise', slug: 'surfers-paradise' },
            { title: 'Upper Coomera', slug: 'upper-coomera' },
            { title: 'Varsity Lakes', slug: 'varsity-lakes' },
        ],
    },
    {
        title: 'Office',
        href: 'office-cleaning',
        slug: 'office-cleaning',
        meta: {},
        items: [
            { title: 'Benowa', slug: '' },
            { title: 'Broadbeach', slug: 'broadbeach' },
            { title: 'Burleigh Heads', slug: 'burleigh-heads' },
            { title: 'Burleigh Waters', slug: 'burleigh-waters' },
            { title: 'Coolangatta', slug: 'coolangatta' },
            { title: 'Currumbin', slug: 'currumbin' },
            { title: 'Helensvale', slug: 'helensvale' },
            { title: 'Hope Island', slug: 'hope-island' },
            { title: 'Labrador', slug: 'labrador' },
            { title: 'Mermaid Waters', slug: 'mermaid-waters' },
            { title: 'Miami', slug: 'miami' },
            { title: 'Mudgeeraba', slug: 'mudgeeraba' },
            { title: 'Nerang', slug: 'nerang' },
            { title: 'Ormeau', slug: 'Ormeau' },
            { title: 'Oxenford', slug: 'oxenford' },
            { title: 'Pacific Pines', slug: 'pacific-pines' },
            { title: 'Palm Beach', slug: 'palm-beach' },
            { title: 'Paradise Point', slug: 'paradise-point' },
            { title: 'Robina', slug: 'robina' },
            { title: 'Runaway Bay', slug: 'runaway-bay' },
            { title: 'Southport', slug: 'southport' },
            { title: 'Surfers Paradise', slug: 'surfers-paradise' },
            { title: 'Upper Coomera', slug: 'upper-coomera' },
            { title: 'Varsity Lakes', slug: 'varsity-lakes' },
        ],
    },
    {
        title: 'Carpet',
        href: 'carpet-cleaning',
        slug: 'carpet-cleaning',
        meta: {},
        items: [
            { title: 'Benowa', slug: '' },
            { title: 'Broadbeach', slug: 'broadbeach' },
            { title: 'Burleigh Heads', slug: 'burleigh-heads' },
            { title: 'Burleigh Waters', slug: 'burleigh-waters' },
            { title: 'Coolangatta', slug: 'coolangatta' },
            { title: 'Currumbin', slug: 'currumbin' },
            { title: 'Helensvale', slug: 'helensvale' },
            { title: 'Hope Island', slug: 'hope-island' },
            { title: 'Labrador', slug: 'labrador' },
            { title: 'Mermaid Waters', slug: 'mermaid-waters' },
            { title: 'Miami', slug: 'miami' },
            { title: 'Mudgeeraba', slug: 'mudgeeraba' },
            { title: 'Nerang', slug: 'nerang' },
            { title: 'Ormeau', slug: 'Ormeau' },
            { title: 'Oxenford', slug: 'oxenford' },
            { title: 'Pacific Pines', slug: 'pacific-pines' },
            { title: 'Palm Beach', slug: 'palm-beach' },
            { title: 'Paradise Point', slug: 'paradise-point' },
            { title: 'Robina', slug: 'robina' },
            { title: 'Runaway Bay', slug: 'runaway-bay' },
            { title: 'Southport', slug: 'southport' },
            { title: 'Surfers Paradise', slug: 'surfers-paradise' },
            { title: 'Upper Coomera', slug: 'upper-coomera' },
            { title: 'Varsity Lakes', slug: 'varsity-lakes' },
        ],
    },
];

export const cities = ['Gold Coast'];
